# ----
# Site

title: Vue Cordova
description: Vue.js plugin for Cordova
url: http://kartsims.github.io/vue-cordova
google_analytics_key:
permalink: pretty

collections:
  documentation:
    title: Documentation
    position: 1
  plugins:
    title: Plugins
    position: 2
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
